{{- if .Values.httploadgen.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "teastore.httploadgen.fullname" . }}
  labels:
    {{- include "teastore.labels" . | nindent 4 }}
    app.kubernetes.io/component: httploadgen
spec:
  replicas: {{ .Values.httploadgen.replicaCount }}
  selector:
    matchLabels:
      {{- include "teastore.httploadgen.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "teastore.httploadgen.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      {{- include "teastore.initContainer.waitForRegistry" . | nindent 6 }}
      containers:
        - name: httploadgen
          image: {{ include "teastore.image" (dict "imageConfig" .Values.httploadgen.image "global" .Values.global "Chart" .Chart) }}
          imagePullPolicy: {{ include "teastore.imagePullPolicy" (dict "imageConfig" .Values.httploadgen.image "global" .Values.global) }}
          ports:
            - name: loadgen
              containerPort: 24226
              protocol: TCP
          resources:
            {{- toYaml .Values.httploadgen.resources | nindent 12 }}
      {{- with .Values.httploadgen.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
